### ISSUE TITLE
Production companies

### ISSUE THREAD

**Issue by IDerr** [OpenTSDB/opentsdb.net#101]
Make a footer or a page showing all companies using opentsdb in production like said 
https://github.com/OpenTSDB/opentsdb/issues/946

https://www.elastic.co/fr/use-cases

**Comment by mbrukman** [comment]
Mentioned on the original bug, here's an existing list of companies:
https://github.com/OpenTSDB/opentsdb/wiki/Companies-using-OpenTSDB-in-production
