### ISSUE TITLE
TCollector doc page outdated?

### ISSUE THREAD

**Issue by HariSekhon** [OpenTSDB/opentsdb.net#108]
Hi,

I think the TCollector page is out of date as it references editing TSD_HOST in startstop but I don't see this in the github repo.

I also noticed some TCollector plugins are not listed on the page, such as Docker, Hadoop NameNode and HBase Master.

Thanks

Hari

**Comment by vasiliyk** [comment]
I have updated tcollector page https://opentsdb.net/docs/build/html/user_guide/utilities/tcollector.html
Please, let me know if anything can be improved.

**Comment by HariSekhon** [comment]
Cert vs DNS URL is broken when going to the https://opentsdb.net/docs/build/html/user_guide/utilities/tcollector.html URL:

<img width="545" alt="Screenshot 2024-10-03 at 00 08 46" src="https://github.com/user-attachments/assets/e3d63120-f78f-430f-b95f-2000d7341128">

**Comment by vasiliyk** [comment]
Hari, It should work now, could you please check again?
