### ISSUE TITLE
opentsdb.net has wrong DNS A record

### ISSUE THREAD

**Issue by ykawamot** [OpenTSDB/opentsdb.net#124]
There is no IP address of GitHub Pages in the A record of opentsdb.net. So, I cannot access https://opentsdb.net/ due to a warning that the SSL certificate is invalid.

```
$ dig opentsdb.net +noall +answer

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.el7_9.5 <<>> opentsdb.net +noall +answer
;; global options: +cmd
opentsdb.net.		3554	IN	A	192.30.252.153
```

You need to set the following IP address in the A record.

```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain

**Comment by aggieben** [comment]
Same problem for me.  Work network blocks this and I have no ability to tell the browser "I don't care"

**Comment by vasiliyk** [comment]
DNS A record updated.
