### ISSUE TITLE
Configuration properties list has disappeared from OpenTSDB 2.4 Configuration page

### ISSUE THREAD

**Issue by colbyguan** [OpenTSDB/opentsdb.net#126]
URL: http://opentsdb.net/docs/build/html/user_guide/configuration.html
Older snapshot: https://web.archive.org/web/20201022122345/http://opentsdb.net/docs/build/html/user_guide/configuration.html 

The very useful list of properties were there, they seem to have disappeared

@manolama

**Comment by manolama** [comment]
Yup, sorry I screwed it up and our friends at Yahoo Japan fixed it. Thanks!
