### ISSUE TITLE
install instructions point to missing opentsdb.conf ?

### ISSUE THREAD

**Issue by 1tylermitchell** [OpenTSDB/opentsdb.net#14]
Hi, is it just me or is this wrong?
"we highly recommend that you create a configuration file based on the config included at ./src/opentsdb.conf"
I'm just starting to look at configuration files but not finding any samples like this one.  Tips?

**Comment by tsuna** [comment]
I see it: https://github.com/OpenTSDB/opentsdb/blob/next/src/opentsdb.conf
Maybe you're looking on the `master` branch instead of `next`, where 2.0 is currently (until it's GA).

**Comment by 1tylermitchell** [comment]
Always good to know it's just me ;).  Sorry, not used to branches yet!
