### ISSUE TITLE
Bug on "Self monitoring" section in Getting Started page

### ISSUE THREAD

**Issue by uprush** [OpenTSDB/opentsdb.net#4]
On the "Self monitoring" section in Getting Started page, the script creating metrics in OpenTSDB has a bug. It only echo the `tsdb mkmetric` command but does not create metrics actually.
The code is `xargs echo ./tsdb mkmetric`, we should remove the `echo` command here.

**Comment by tsuna** [comment]
Thanks for the report.  Sorry at first I didn't actually notice you sent a pull request, in my email I thought it was only a bug report, so I mistakenly committed a separate change.  Not that this really matters though, but just saying.
