### ISSUE TITLE
Missing gui_graphing_style.jpg

### ISSUE THREAD

**Issue by trodery** [OpenTSDB/opentsdb.net#51]
I searched the repository but couldn't find gui_graphing_style.jpg

It's missing from this page: http://opentsdb.net/docs/build/html/user_guide/guis/index.html

**Comment by tsuna** [comment]
Yeah I don't have that one either.  @manolama ?

**Comment by manolama** [comment]
Drats, I can't find it. I'll have to create a new image, thanks for catching that!
