### ISSUE TITLE
Documentation link to wrong index file?

### ISSUE THREAD

**Issue by trodery** [OpenTSDB/opentsdb.net#52]
I'm wondering if the "index" link at the bottom of http://opentsdb.net/docs/build/html/index.html should point back to itself or if it should indeed go to http://opentsdb.net/docs/build/html/genindex.html.

genindex.html is basically blank except for the site template.

**Comment by tsuna** [comment]
Uh, weird. @manolama is that Sphinx not generating the index properly?

**Comment by manolama** [comment]
Good catch, that is strange. It's all auto generated by Sphinx but maybe I missed setting something up. I'll poke around a bit and see what's what.
