### ISSUE TITLE
Downsampling timestamp

### ISSUE THREAD

**Issue by nhahtdh** [OpenTSDB/opentsdb.net#69]
According to http://opentsdb.net/docs/build/html/user_guide/query/aggregators.html#downsampling:

> The actual time stamps for the new data points will be an average of the time stamps for each data point in the time span. Future versions of OpenTSDB will likely normalize this time on a well defined boundary.

Does this commit https://github.com/OpenTSDB/opentsdb/commit/9c35480d46881c86745eff46ae607f66d207c9b4 fixed this issue?

**Comment by manolama** [comment]
Yes, updated the doc in 1c2c53aab0f4715923f17c1aa7408ecd255de476
